version: 2
jobs:
  build:
    docker:
      - image: cypress/browsers:chrome67

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - ~/.cache
            - ~/.npm
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run tests:integration
      - run: npm run test:ci:api
      - run: npm run test:ci:frontend